name: Infection
version: '${version}'
main: org.yanmachine.infection.main.Infection
api-version: '1.20'

commands:
  infection:
    description: Infected game mode commands
    usage: /infection <arguments>